# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 640)
        Form.setStyleSheet("background-image: url(\'C:/Users/LattePanda/Desktop/firstbg.jPG\');\n"
"border: 0px;")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(350, 600, 450, 600))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{background-image: url(\'C:/Users/LattePanda/Desktop/bookicon_2.jPG\');\n"
"border: 0px;\n"
"border-radius:30px;\n"
"opacity:50;}\n"
"QPushButton:hover{\n"
"background-image: url(\'C:/Users/LattePanda/Desktop/bookicon.jPG\');\n"
"border: 0px;\n"
"border-radius:30px;\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(420,970, 400, 300))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background:transparent;\n"
"color:rgba(11, 32, 112, 150);\n"
"font-weight:bold;")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "시작하기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.showMaximized()
    sys.exit(app.exec_())
