# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(592, 393)
        Form.setStyleSheet("background-image: url(\'C:/Users/LattePanda/Desktop/fourth.JPG\');\n"
"border: 0px;")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 120, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background:transparent;\n"
"color:rgba(0, 57, 0, 100);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(90, 190, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background:transparent;\n"
"color:rgba(0, 57, 0, 100);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(210, 110, 291, 41))
        self.textEdit.setStyleSheet("background:transparent;\n"
"border: 2px solid rgb(0, 65, 50);")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(210, 180, 291, 41))
        self.textEdit_2.setStyleSheet("background:transparent;\n"
"border: 2px solid rgb(0, 65, 50);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(110, 270, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background:transparent;\n"
"background-color:white;\n"
"border: 3px solid white;\n"
"border-radius:15px;\n"
"color:rgba(0, 67, 0, 180);\n"
"}\n"
"QPushButton:hover{\n"
"background:transparent;\n"
"background-color:white;\n"
"border: 3px solid white;\n"
"border-radius:15px;\n"
"color:rgba(0, 67, 0, 180);\n"
"font-size:24pt;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 270, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background:transparent;\n"
"background-color:white;\n"
"border: 3px solid white;\n"
"border-radius:15px;\n"
"color:rgba(0, 67, 0, 180);\n"
"}\n"
"QPushButton:hover{\n"
"background:transparent;\n"
"background-color:white;\n"
"border: 3px solid white;\n"
"border-radius:15px;\n"
"color:rgba(0, 67, 0, 180);\n"
"font-size:24pt;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "아이디"))
        self.label_3.setText(_translate("Form", "비밀번호"))
        self.pushButton.setText(_translate("Form", "확인"))
        self.pushButton_2.setText(_translate("Form", "취소"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
